feat: 모집공고 작성 임시저장 기능 구현
Ludo-SMP/ludo-frontend pull request #166
Opened 2024-04-20 05:53 UTC by hyosin-Jang

<strong>closes #165</strong>

## 💡 다음 이슈를 해결했어요.
임시저장 기능 구현

## 💡 이슈를 처리하면서 추가된 코드가 있어요.

### 1. 임시저장하기 버튼 클릭한 경우
- savedKey로 localStorage에 값을 저장합니다. (key 관련 자세한 내용은  #165 를 참고해주세요.)

### 2. 마이페이지 > 임시저장 목록
- 마이페이지의 임시저장 목록을 보시면 스터디 탭과 모집공고 탭으로 나뉘어져 있습니다. 
- 선택된 카드에 따라 localStorage에서 해당 카드를 포함하는 리스트만 추출해서 뿌려줬습니다.

```  
const getTempList = (selectedCard: 'STUDY' | 'RECRUITMENT') => {
    // TODO: 스터디 타입도 추가
    const savedList: Array<Partial<RecruitmentForm> & { savedKey: string }> = [];
    for (const key in window.localStorage) {
      // hasOwnProperty로 빌트인 속성 제거
      if (window.localStorage.hasOwnProperty(key) && key.toUpperCase().includes(selectedCard)) {
        savedList.push({ ...JSON.parse(localStorage.getItem(key)), savedKey: key });
      }
    }
    return savedList;
  };
```

### 3. 임시저장 글 이어서 작성하기

- 카드를 클릭하면 이어서 작성할 수 있고 페이지가 전환됩니다. 이때, 선택한 카드의 값을 받아오기 위해 savedKey를 store에 저장했습니다.
```
export interface SavedKeyState {
  savedKey: string;
  setSavedKey: (newKey: string) => void;
}

// 선택된 카드 키
export const useSavedKeyStore = create<SavedKeyState>((set) => ({
  savedKey: '',
  setSavedKey: (newKey: string) => set(() => ({ savedKey: newKey })),
}));

```

스터디 모집공고 페이지에서는 임시저장된 키가 있는 경우, `getDefVal` 함수를 통해 초기값을 `<Select>` 또는 `<Input>`에 들어가는 형태로 가공해줍니다.
- ex. applicationCount: 3 -> { label: '3명', value: 3 }

```
  // 임시저장된 키가 있는지 확인
  const savedKey = useSavedKeyStore((state) => state.savedKey);
  const setSavedKey = useSavedKeyStore((state) => state.setSavedKey);

 // 키로 조회한 임시저장된 form 값
  const tempSaved: RecruitmentForm | null = JSON.parse(localStorage.getItem(savedKey)) ?? null;

  const getDefVal = (formKey: keyof RecruitmentForm) => {
    if (!tempSaved) return;
    const val = tempSaved[formKey];

    switch (formKey) {
     // -- 1) select 경우 { value: '', label: '' } 형태
      case 'applicantCount': {
        return APPLICATION_CNT.find((el) => el.value === val) ?? null;
      }
      case 'positionIds': {
        return POSITION.find((el) => el.value === val) ?? null;
      }
      case 'stackIds': {
        return STACK.find((el) => el.value === val) ?? null;
      }
      case 'contact': {
        return CONTACT.find((el) => el.value === val) ?? null;
      }
     // --2) input의 경우 string 형태
      default: {
        return val;
      }
    }
  };
```

-  임시저장 목록에서 이어서 작성한 후, 스터디 새로 생성 시 값이 채워지는 것 방지하기 위해 언마운트될 때 선택된 키를 초기화해줍니다. 

```
  useEffect(() => {
    window.scrollTo(0, 0);
    return () => {
      // 언마운트될 때, 임시저장 선택된 키 초기화
      if (tempSaved) setSavedKey('');
    };
  }, [pathname]);
```

### 💡 필요한 후속작업이 있어요.
- [ ] 임시저장 목록 uuid 시간순으로 정렬
- [ ] 임시저장 목록 > title 빈 경우 처리
- [ ] 브랜치 전환 시 생성되는 yarn/cache/**/* 파일들, (제가 설정을 잘못한걸 수도 있는데 yarn 3.x를 사용하면서 nodeLinker가 pnp가 아닌 node-modules로 되어 있습니다. zero-install인 경우 yarn/cache도 같이 레포에 올려주는 것으로 알고 있는데 다른 분들은 이 부분 문제 없으신지 궁금합니다.)
- [ ] yarn.lock 충돌
- [ ] DOM 관련 브라우저 warning들 (isOpen,)
<br><br>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-04-24 12:08 UTC, SungHyun627 commented
commit을 작은 단위까지 세밀히 작성하신 것 같네요!!. 덕분에 작업 흐름을 쉽게 알 수 있었던 것 같습니다👍. 임시저장 부분도 구현 잘해주신 것 같아요. 임시저장 글을 최신순으로 정렬하기 위해 현재 시간과 랜덤한 MAC 주소로 생성되는 uuid v1을 사용하신 부분과 이어서 작성한 글을 임시저장 할 경우 새로운 key를 발급하는 부분에서, 기능구현을 위해 많은 고민을 하신 게 느껴지네요😃.
마이페이지에서 임시 저장글을 삭제하는 부분에서 발생한 버그같은 경우에는, 모달의 state를 전역으로 관리한는 문제와 모달 활성화 로직이 지저분한 문제 때문에 발생한 것 같습니다 ㅠㅠㅠ. 이 부분은 추후에 전반적인 리팩토링이 필요할 것 같아요!!.
스터디 모집공고 작성 및 수정 페이지 레이아웃 기능 구현, 임시저장 기능 구현하시느라 수고 많으셨습니다!!👍

2024-04-24 13:15 UTC, abiriadev commented
@hyosin-Jang PR에 들어간 예시 코드에 하이라이팅 추가했어요!

2024-04-24 14:33 UTC, abiriadev commented
`saveTemporary` 함수를 스터디에서도 사용할 수 있도록 분리했습니다!

2024-04-30 05:40 UTC, abiriadev commented on src/Components/Calendar/EndDate.tsx
> +    const today = new Date(Date.now());
```suggestion
    const today = new Date();
```

`new Date()`로 새 Date 객체를 생성할 때, 인자가 없으면 기본적으로 현재 시간(now을) 기준으로 생성합니다.
따라서 위 코드를 정확히 같은 내용을 객체를 두 번씩 생성하며 반복하게 됩니다.

참고: 
https://stackoverflow.com/a/66925958/16246435

2024-04-30 05:50 UTC, abiriadev requested changes

2024-04-30 05:50 UTC, abiriadev commented on src/Components/Calendar/EndDate.tsx
> +    const today = new Date(Date.now());
```suggestion
    const today = new Date();
```

`new Date()`로 새 Date 객체를 생성할 때, 인자가 없으면 기본적으로 현재 시간(now을) 기준으로 생성합니다.
따라서 위 코드를 정확히 같은 내용을 객체를 두 번씩 생성하며 반복하게 됩니다.

참고: 
https://stackoverflow.com/a/66925958/16246435

2024-04-30 05:51 UTC, abiriadev commented on src/Components/Calendar/EndDate.tsx
> +    const today = new Date(Date.now());
(실수로 comment로 올려서 지웠다가 다시 올렸습니다)

2024-04-30 09:30 UTC, abiriadev requested changes
`LabelForm` 컴포넌트를 제네릭하게 만드는, 따라서 재사용성을 높이는 방식의 수정 제안입니다!

사실 많이 수정하기 힘드실 수도 있으니 간단하게 살펴만 보시고 의견 말씀해 주세요!

2024-04-30 09:30 UTC, abiriadev commented on src/Components/Common/LabelForm/index.tsx
> +import { RecruitFormWithSelect } from '@/Types/study';
```suggestion
```
`Components/Common` 폴더 아래의 컴포넌트들에는 특정 타입에 대한 종속성은 가급적 넣지 않는 게 재사용에 유리해 보여요!

2024-04-30 09:30 UTC, abiriadev commented on src/Components/Common/LabelForm/index.tsx
> +import { FieldErrors } from 'react-hook-form';
```suggestion
import { FieldErrors, FieldValues } from 'react-hook-form';
```

범용 `FieldValues` 타입을 RHF으로부터 가져옵니다

2024-04-30 09:30 UTC, abiriadev commented on src/Components/Common/LabelForm/index.tsx
> +export const LabelForm = ({ label, children, name, errors }: LabelFormProps<RecruitFormWithSelect>) => {
```suggestion
export const LabelForm = <T extends FieldValues = FieldValues>({ label, children, name, errors }: LabelFormProps<T>) => {
```

`LabelForm`을 제네릭하게 만듭니다.

2024-04-30 09:30 UTC, abiriadev commented on src/Pages/CreateRecruitment/page.tsx
> +`;
```suggestion
```

`ErrorMsg` 이동

2024-04-30 09:30 UTC, abiriadev commented on src/Components/Common/LabelForm/index.tsx
> +`;
```suggestion
`;

export const ErrorMsg = styled.p`
  color: ${({ theme }) => theme.color.negative};
`;
```

`ErrorMsg` 이동

2024-04-30 09:30 UTC, abiriadev commented on src/Components/Common/LabelForm/index.tsx
> +import { ErrorMsg } from '@/Pages/CreateRecruitment/page';
```suggestion
```
`ErrorMsg`를 페이지에서 공용 컴포넌트(`LabelForm`)으로 이동

2024-04-30 09:59 UTC, hyosin-Jang commented on src/Components/Calendar/EndDate.tsx
> +    const today = new Date(Date.now());
말씀하신대로 기본값이 현재 시간을 기준으로 생성되니까 인자를 제거해도 될 것 같습니다. 수정했습니다!

2024-04-30 10:08 UTC, hyosin-Jang commented on src/Components/Common/LabelForm/index.tsx
> +import { RecruitFormWithSelect } from '@/Types/study';
저도 이 부분 타입 종속성 때문에 고민했었는데 rhf에서 범용 FieldValues 타입을 제공하는군요
재사용성을 고려하면 제네릭으로 수정하는게 좋을 것 같습니다 반영하겠습니다 👍

2024-04-30 10:56 UTC, hyosin-Jang commented on src/Pages/CreateRecruitment/page.tsx
> +`;
에러 메시지는 `RHF`와 값 관리를 따로 하는 스택 모달 (자체 state 사용) 도 사용하고 있어서 `page`에 두었는데요,
에러 메시지까지 같이 보여주는 `<LabelForm>`의 역할을 생각하면 위치를 `<LabelForm>`으로 이동하는게 자연스러운 것 같네요
이것도 반영했습니다! 🙏

2024-04-30 11:03 UTC, abiriadev requested changes

2024-04-30 11:03 UTC, abiriadev commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
```suggestion
                <LabelForm label="연결 url" name="callUrl" errors={errors}>
```

name이 빠져있어 연결 URL의 validation이 올바르게 동작하지 않습니다.

아래 사진은 피그마 디자인 시안입니다.

![image](https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/2fa7425d-e912-4789-a17b-3c2423d05cb0)

아래 사진은 로컬에서의 테스트 결과입니다.

![image](https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/97cd2b42-0cfe-465a-b97c-9b5e1d7eaa18)

2024-04-30 11:04 UTC, abiriadev commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
아 지금 보니까 기술 스택 부분도 validation이 빠진 것 같아요!

![image](https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/ce076722-32e9-4d76-af59-3ef08de800df)

2024-04-30 11:05 UTC, abiriadev commented on src/Pages/CreateRecruitment/page.tsx
> +`;
@hyosin-Jang 확인해주셔서 감사합니다!

2024-04-30 11:16 UTC, hyosin-Jang commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
앗 callUrl name을 등록하는 걸 놓쳤네요. 반영하겠습니다 확인 감사해요!

`props`로 `error`랑 `name`은 같이 전달이되어야 하는데요, 혹시 둘중 하나가 누락된 경우 타입으로 체크하는 방법이 있을까요? 🤔

2024-04-30 11:27 UTC, abiriadev commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
글쎄요... 일단 이런 방법이 있지 않을까요?

```ts
{ a: T, b: T } | { ... }
```

이렇게 하면 `a`또는 `b` 둘다 있거나 둘다 아예 없거나 하는 경우만 통과되는 것으로 알긴 하지만, 좀더 같이 더 나은 방법을 테스트해보면 좋을 것 같아요!

예를 들면 error를 처음부터 받아서 factory pattern 형태로 만든다던가... 그럼 항상 error가 항상 들어가 있겠죠?
아니면 `useContext`로 에러를 주는 방법도 있는데 그건 너무 복잡할 거 같고... 저도 명확한 해결책은 떠오르지가 않네요.

2024-04-30 11:45 UTC, hyosin-Jang commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
기술 스택 validation은 이슈가 있어서 조금 찾아보고 있었습니다.
기존에는 `onSubmit`을 호출한 시점에 기술스택 선택이 안된 경우, 에러메시지를 띄우는 순서로 작업을 했습니다.

그런데, `RHF`는 `onSubmit`을 호출하기 전에 유효성 검사를 하기 때문에, 유효하지 않은 값이 있는 경우 
`onSubmit`이 실행되지 않는 문제가 있었어요. 
(rhf에서 관리하는 값들이 다 validate된 후에, onSubmit 호출 가능 -> 기술스택 validation 로직 실행)

2024-04-30 11:46 UTC, hyosin-Jang commented on src/Pages/CreateRecruitment/page.tsx
> +                <LabelForm label="연결 url" errors={errors}>
찾아보니 `handleSubmit` 두번째 인자로 `onError`를 넘길 수 있어서 해당 함수에 기술스택 validataion 로직 추가했습니다 
확인 감사해요! 🙂

참고: https://github.com/orgs/react-hook-form/discussions/8372

2024-05-07 05:07 UTC, abiriadev approved these changes
RHF를 굉장히 자세하게 조사해보신 점 멋집니다.

수고하셨습니다.

2024-05-07 09:43 UTC, merged