feat: 스택 검색 기능 구현
Ludo-SMP/ludo-frontend pull request #168
Opened 2024-04-21 15:02 UTC by SungHyun627

**Closes #158**

## 💡 다음 이슈를 해결했어요.
- [x] 스택 검색 기능 구현
- [x] 수정된 모달 컴포넌트 디자인을 반영하여 반응형으로 구현 

## 💡 이슈를 처리하면서 추가된 코드가 있어요.

## 💡 필요한 후속작업이 있어요.

## 💡 다음 자료를 참고하면 좋아요.

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-04-30 06:25 UTC, abiriadev commented
@SungHyun627 
![image](https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/239f344f-8012-4eab-932d-c46fb676a356)

폼 페이지들에서 스택 모달이 흰색 배경하고 살짝 구분이 어려운 문제가 있다고 느꼈는데
1. box-shadow
2. border
3. backdrop

등을 추가해서 모달을 구분시켜보는 건 어떻게 생각하시나요?

2024-04-30 07:11 UTC, SungHyun627 commented
> @SungHyun627 ![image](https://private-user-images.githubusercontent.com/72962900/326692547-239f344f-8012-4eab-932d-c46fb676a356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjA4MjQsIm5iZiI6MTcxNDQ2MDUyNCwicGF0aCI6Ii83Mjk2MjkwMC8zMjY2OTI1NDctMjM5ZjM0NGYtODAxMi00ZWFiLTkzMmQtYzQ2ZmI2NzZhMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA3MDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTc0OTg3ZGY0Nzg0MDU5ZTk2MzBkZWQzZTgxZmUzMmUyOWEwY2Q4NGViNTdhYjE0NmMyNTg4MTQ2OTI0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXL-9Juf8gY_IkH552spgOOKaVKg9H7nxeWoNWRo3C0)
> 
> 폼 페이지들에서 스택 모달이 흰색 배경하고 살짝 구분이 어려운 문제가 있다고 느꼈는데
> 
> 1. box-shadow
> 2. border
> 3. backdrop
> 
> 등을 추가해서 모달을 구분시켜보는 건 어떻게 생각하시나요?

@abiriadev
동의합니다. 사실 backdrop이 가장 깔끔할 것 같기는 한데, 코드 수정이 많이 필요할 것 같아서, shadow로 처리하면 좋을 것 같습니다. 이 부분은 포키님과도 이야기가 필요할 듯 하네요. 현재 border는 `border: 1px solid ${({ theme }) => theme.color.black1};` 다음과 같이 설정되어 있는데, 색이 연해서 잘 티가 안나는 것 같습니다ㅠㅠ

### ✔︎ box-shadow 적용 안시켰을 때
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/62270427/6e991c1d-7bbe-4a35-b62b-10e8d772fa23">

### ✔︎ `box-shadow: 0px 0px 10px 0px ${(props) => props.theme.color.black1}` 적용 시
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/62270427/8ff8ce03-993f-40ff-ab30-2c5081d9a1cb">

2024-04-30 08:29 UTC, abiriadev commented
> 이 부분은 포키님과도 이야기가 필요할 듯 하네요.

오늘 회의 때에도 잠시 시간 나시면 이것 관련해서 얘기해 보셔도 좋을 것 같습니다!

2024-05-01 12:26 UTC, abiriadev requested changes

2024-05-01 12:26 UTC, abiriadev commented on src/Assets/index.tsx
> +export { default as Setting } from './icons/setting.svg?react';
`StudyThumbnail` 과 `Setting` 아이콘이 storybook에 추가되어야 할 것 같아요!

2024-05-01 12:47 UTC, abiriadev commented on src/Types/study.ts
> +
유틸 느낌이 강한데 다른 코드에서도 쓸 수 있도록 해보는 것은 어떨까요?

2024-05-01 13:26 UTC, SungHyun627 commented on src/Assets/index.tsx
> +export { default as Setting } from './icons/setting.svg?react';
StudyThumbnail과 Setting 아이콘 Storybook에 반영 완료하였습니다.

2024-05-01 13:32 UTC, SungHyun627 commented on src/Types/study.ts
> +
현재 사용되고 있지는 않지만, 추후에 사용될 가능성이 농후해 보입니다. 해당 interface를 atom.ts 파일에 위치시키는 것도 고려해 보면 좋을 것 같습니다.🤔

2024-05-01 13:46 UTC, hyosin-Jang approved these changes

2024-05-01 13:47 UTC, abiriadev approved these changes
수고하셨습니다! :+1:

2024-05-01 13:48 UTC, merged