fix: 401 에러 발생 시 로그아웃 처리
Ludo-SMP/ludo-frontend pull request #170
Opened 2024-04-24 02:44 UTC by hyosin-Jang

### 💡 다음 이슈를 해결했어요.

- [x] msw로 401 응답 테스트
- [x] error.response.status가 401인 경우 logout api 호출
- [x] 서비스 워커 등록 시, async로 처리하도록 수정. promise resolve된 후, DOM 렌더링 진행
(서비스 워커 등록 전 렌더링할 경우, 실제 요청과 race condition할 수 있음)
- [x] axios.response.interceptor에서 error를 reject해서 LoginProvider에서 에러 캐치 후, 유저 정보 리셋하는 순서

<br><br>
### 💡 이슈를 처리하면서 추가된 코드가 있어요.

```
  axiosInstance.interceptors.response.use(
    (response) => {
      return response;
    },
    async (error: AxiosError) => {
      if (error.response?.status === HttpStatus.UNAUTHORIZED) {
        try {
          const data = await logOut(); // 로그아웃 통해 쿠키 제거
          if (data) window.location.href = '/';
        } catch {}
      }
     // Login Provider에서 에러 핸들링하도록 reject 합니다.
      return Promise.reject(error);
    },
  );

```

### 💡 필요한 후속작업이 있어요.
- 서버 배포한 다음 잘 동작하는지 테스트해야 합니다.

<br/>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-04-24 12:19 UTC, SungHyun627 commented
msw를 사용하여 mock handler 작성 후 401 테스트 작업 하신 부분, util의 axios instance를 생성하는 코드에서 401 error를 reject 처리해서 LoginProvider로 넘기신 부분 확인했습니다👍. 이전에 놓치고 지나간 에러인데, 꼼꼼히 체크해주셨네요!! 감사합니다🙏

2024-04-24 12:59 UTC, abiriadev approved these changes, later dismissed

2024-04-24 12:59 UTC, abiriadev commented on src/index.tsx
> +// async function enableMocking() {
사용하지 않는 코드는 지우셔도 좋을 것 같아요!

2024-04-24 13:45 UTC, abiriadev requested changes

2024-04-24 13:45 UTC, abiriadev commented on src/index.tsx
> +// enableMocking().then(() => ReactDOM.createRoot(document.getElementById('root')!).render(<App />));
```suggestion
```

사용되지 않는 코드는 지워도 좋을 것 같아요!

2024-04-27 00:13 UTC, abiriadev approved these changes

2024-04-27 03:40 UTC, merged