아코디언 컴포넌트 구현
Ludo-SMP/ludo-frontend pull request #179
Opened 2024-05-10 15:02 UTC by hyosin-Jang

closes #178 

### 💡 다음 이슈를 해결했어요.

- 아코디언이 열린 경우, 화살표 180도 회전합니다.
- 열릴 때랑 닫힐 때, transition을 적용해서 스르륵 열립니다.
- AccordionDetail( 펼쳤을 때 나오는 내용)의 height가 길면 스르륵 열릴 때, 시간이 오래걸리는 문제가 있어서 contentHeight 을 구하는 ref를 달았습니다. 
-  Accordion 써머리의 제목이나 내용이 width를 초과할 경우, 잘리는 내용을 "..." 으로 표시했습니다.

### 실행영상

https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/af251f36-31aa-4b33-a14e-ff34b22cec3d

### Accordion 써머리의 제목이나 내용이 width를 초과할 경우, 잘리는 내용을 "..." 으로 표시

https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/211c8c6d-d89b-4180-bce6-a42f53584f64

### 제목만 있는 경우
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/ba177dc6-99ad-42c2-b64c-be1bdc6e091e">

### 제목 + 설명이 있는 경우
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/a46adf69-5330-47ba-a4fc-45d4316651f5">

### 💡 필요한 후속작업이 있어요.
- typography 브랜치 머지 후 타이포 적용

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [x] 변경 후 코드는 기존의 테스트를 통과합니다.
- [x] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-05-13 02:13 UTC, abiriadev requested changes
아코디언을 펼칠 때 간단한 트랜지션을 추가해서 사용자들이 아코디언을 더욱 잘 인식할 수 있도록 했어요!

https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/03525c65-b727-4d28-ac4b-3c221495ca12

2024-05-13 02:13 UTC, abiriadev commented on src/Assets/SelectArrow.tsx
> +      xmlns="http://www.w3.org/2000/svg"
회전 트랜지션 추가

```suggestion
      xmlns="http://www.w3.org/2000/svg"
      style={{
        transition: 'transform 0.3s ease',
      }}
```

2024-05-13 11:55 UTC, abiriadev approved these changes
- SVG 컴포넌트에 방향을 적용하신 아이디어가 독창적입니다.
- styled component의 `css` 함수를 필요에 맞게 응용하신 점이 대단하십니다.

2024-05-14 03:32 UTC, hyosin-Jang commented
> > * 아코디언이 열린 경우, 화살표 180도 회전합니다.
> > * 열릴 때랑 닫힐 때, transition을 적용해서 스르륵 열립니다.
> 
> 아코디언을 펼칠 때 회전하는 화살표에도 transition을 적용해서 사용자가 통일감을 느낄 수 있도록 했어요!
> 
>  acc-00.00.02.085-00.00.05.673.mp4

@abiriadev 화살표에도 transition을 적용할 수 있다니 멋지네요. 매번 좋은 제안 주셔서 감사드립니다! 🙏🙏

2024-05-14 03:32 UTC, merged