평가 문항 컴포넌트(ReviewQuestion) 구현
Ludo-SMP/ludo-frontend pull request #184
Opened 2024-05-13 03:56 UTC by SungHyun627

### 💡 다음 이슈를 해결했어요.

<br>
### 💡 이슈를 처리하면서 추가된 코드가 있어요.

✔︎ 체크되지 않은 상태
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/62270427/13e620a7-dd3b-402f-be54-9542c5ce3b07">

✔︎ 각 문항이 체크된 상태
<img width="500" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/62270427/c3baddf9-a286-4dbd-8352-c1d016d3428e">

### 💡 필요한 후속작업이 있어요.
<br>

### 💡 다음 자료를 참고하면 좋아요.
- [[React.js] Radio, Checkbox 커스텀](https://velog.io/@dlwjdcks11/React.js-Radio-Checkbox-%EC%BB%A4%EC%8A%A4%ED%85%80#%EA%B8%B0%EB%B3%B8-%EA%B5%AC%EC%A1%B0-1)
- [Styling Radio Buttons with CSS (59 Custom Examples)](https://www.sliderrevolution.com/resources/styling-radio-buttons/)

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [ ] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-05-13 04:14 UTC, abiriadev requested changes

2024-05-13 04:14 UTC, abiriadev commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +  contents: string[];
```suggestion
  contents: [string, string];
```

현재 단 두 개의 항목만 사용하니 튜플로 쓰는 게 더 명확할 것 같아요!

2024-05-14 06:35 UTC, hyosin-Jang commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +const QuestionTitle = styled.div`
사소하긴 한데 Title은 heading 태그 사용하셔도 좋을 것 같습니다!
섹션으로 구분된 엘리먼트에는 heading 태그를 사용하는것이 SEO에 좋다고 합니다

참고 블로그:
- https://brunch.co.kr/@e9c7009de84443b/9
- https://velog.io/@yooon26/heading-%ED%83%9C%EA%B7%B8-%EC%98%AC%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2024-05-14 07:42 UTC, SungHyun627 commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +const QuestionTitle = styled.div`
넵, 반영하겠습니다!!!

2024-05-14 09:36 UTC, SungHyun627 commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +  contents: string[];
반영했습니다!!

2024-05-14 13:49 UTC, hyosin-Jang commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +  h3 {
제안 반영해주셔서 감사합니다!

다만, <Heading> 컴포넌트가 typography.ts로 통합된 이후, 삭제될 예정이여서
아래처럼만 변경해주셔도 좋을 것 같습니다! 🙂

```
const QuestionTitle = styled.h3`
...
`
```

2024-05-14 13:56 UTC, SungHyun627 commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +  h3 {
```
const QuestionTitle = styled.h3`
  font-family: 'Pretendard500';
  font-size: 18px;
  font-style: normal;
  font-weight: 500;
  line-height: 32px;
  width: 100%;
`;
```
수정했습니다👍

2024-05-14 15:07 UTC, abiriadev commented on src/Components/ReviewQuestion/ReviewQuestion.tsx
> +          {Array.from({ length: optionCnt }, (_, i) => i + 1).map((value: number) => (
`Array.from({ length })`를 사용해 배열을 알아보기 쉽게 만드시는 부분이 인상적이에요!

2024-05-14 15:38 UTC, abiriadev approved these changes

2024-05-14 15:38 UTC, abiriadev commented
수고하셨습니다!

2024-05-15 12:32 UTC, hyosin-Jang approved these changes

2024-05-16 03:34 UTC, merged