페이지 상단 바(TopBar) 컴포넌트 구현
Ludo-SMP/ludo-frontend pull request #186
Opened 2024-05-13 08:54 UTC by SungHyun627

### 💡 다음 이슈를 해결했어요.
- [x] 뒤로 가기 버튼 클릭 시, 이전 페이지로 이동하는 기능 구현
<br>

### 💡 이슈를 처리하면서 추가된 코드가 있어요.

### ✔︎ TopBar 컴포넌트
<img width="250" alt="image" src="https://github.com/Ludo-SMP/ludo-frontend/assets/62270427/3e750815-e10d-4fc4-99e6-e368abebee16">

### 💡 필요한 후속작업이 있어요.
-[ ] 스토리북에서 children으로 컴포넌트를 전달하는 방안 고려

### 💡 다음 자료를 참고하면 좋아요.

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [ ] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-05-14 10:49 UTC, hyosin-Jang requested changes
@SungHyun627 
현님 코드가 정말 깔끔하고 직관적으로 작성되어 있네요! 각 요소들이 목적에 부합하도록 잘 정리되어 있어서 코드를 읽는 데 전혀 어려움이 없었습니다!

아래 링크에도 남겨놨는데 저희가 페이지마다 wrapper 요소의 이름을 다르게 짓고 있어서 혹시 통일해보는 건 어떨까요? 
https://github.com/Ludo-SMP/ludo-frontend/pull/193#pullrequestreview-2054846717

2024-05-14 10:49 UTC, hyosin-Jang commented on src/Components/Topbar/index.tsx
> +const MoveBack = styled.div`
```suggestion
const MoveBack = styled.button`
```

혹시 뒤로가기를 div로 구현하신 이유가 있을까요?

`button`을 사용하면 스크린 리더 등 보조 기기가 해당 아이콘을 버튼으로 인식하여 사용자가 클릭 가능한 버튼임을 인지할 수 있어서 접근성 면에서도 좋을 것 같습니다!

https://techblog.woowahan.com/15541/

2024-05-14 12:03 UTC, SungHyun627 commented on src/Components/Topbar/index.tsx
> +const MoveBack = styled.div`
구현하면서도 찝찝함이 남아있었는데, 접근성을 고려하면 button으로 구현하는 게 맞을 것 같네요!! 감사합니다🙏

2024-05-14 15:20 UTC, abiriadev requested changes

2024-05-14 15:20 UTC, abiriadev commented on src/Components/Topbar/index.tsx
> +      <MoveBack onClick={() => navigate(-1)}>
히스토리에서 뒤로 가기를 `navigate(-1)` 처럼 간결하게 작성할 수 있는지 처음 알았습니다. 좋은 코드 배우고 갑니다!

2024-05-14 15:20 UTC, abiriadev commented on src/Components/Topbar/index.tsx
> +        </svg>
`src/Assets/LeftArrow.tsx`를 사용하시지 않고 새 SVG를 사용하신 이유가 있으신가요?

2024-05-14 15:20 UTC, abiriadev commented on src/Components/Topbar/index.tsx
> +    cursor: pointer;
커서 모양까지 신경쓰시는 꼼꼼한 디테일이 대단하신 것 같아요!

2024-05-14 15:20 UTC, abiriadev commented on src/Components/Topbar/index.tsx
> +`;
```suggestion
const TopbarWrapper = styled.div<{ $gap?: number }>`
  display: flex;
  flex: 1 0 0;
  max-width: 1224px;
  width: 100%;
  align-items: center;
  gap: ${({ $gap }) => `${$gap}px`};
`;
```

다음과 같이 `gap`을 `$gap`으로 선언해서 의도치 않게 \<div\>에 `gap` prop을 전달하는 일을 방지할 수 있을 것 같아요!

> Think of [transient props](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c) as a lightweight, but complementary API to shouldForwardProp. Because styled-components allows any kind of prop to be used for styling (a trait shared by most CSS-in-JS libraries, but not the third party library ecosystem in general), adding a filter for every possible prop you might use can get cumbersome.
> 
> Transient props are a new pattern to pass props that are explicitly consumed only by styled components and are not meant to be passed down to deeper component layers. Here's how you use them:

2024-05-14 15:21 UTC, abiriadev commented
필요한 기능을 잘 수행하는 컴포넌트를 만드신 것 같습니다! 특히 navigation을 잘 활용하신 것 같습니다.

2024-05-16 01:04 UTC, SungHyun627 commented on src/Components/Topbar/index.tsx
> +        </svg>
LeftArrow.tsx랑 figma에 있는 svg랑 약간 다르더라고요 ㅠㅠ

2024-05-16 04:27 UTC, SungHyun627 commented on src/Components/Topbar/index.tsx
> +`;
반영하겠습니다.!!

2024-05-16 04:29 UTC, SungHyun627 commented on src/Components/Topbar/index.tsx
> +    cursor: pointer;
감사합니다!!

2024-05-16 04:30 UTC, merged