알림 미리보기 인박스 구현
Ludo-SMP/ludo-frontend pull request #190
Opened 2024-05-14 06:44 UTC by SungHyun627

**Closes #182**

### 💡 다음 이슈를 해결했어요.
- [ ] 알림 미리보기(AlarmPreview) 컴포넌트 구현
- [ ] 알림 미리보기 인박스 토글 기능 구현
- [ ] 알림이 생성된 시간과 현재 시간을 비교하는 util함수 구현

### 💡 이슈를 처리하면서 추가된 코드가 있어요.
#### ✔︎ 알림 미리보기 컴포넌트 구현
알림 타입, 제목, 세부 내용, 알림 생성날짜를 props로 받는 알림 미리보기 컴포넌트를 구현하였습니다. 이를 이용하여
AlarmInbox 컴포넌트에서 알람 미리보기 정보를 받아, 알림 미리보기 컴포넌트 리스트를 렌더링하는 방식으로 구현했습니다.
```tsx
type AlarmType = 'LUDO' | 'STUDY';

export interface AlarmPreviewProps {
  /** 알람 타입 */
  alarmType: AlarmType;

  /** 알람 제목*/
  title: string;

  /** 알람에 대한 간략한 설명 */
  description: string;

  /** 최초 알림이 생성된 후 경과한 시간 */
  createdAt: string;
}

export const AlarmPreview = ({ alarmType, description, title, createdAt }: AlarmPreviewProps) => {
  return (
    <AlarmPreviewWrapper>
      <ImageWrapper alarmType={alarmType}>
        <img src={alarmType == 'LUDO' ? Logo : DefaultStudyThumbnail} width={32} height={32} />
      </ImageWrapper>
      <SummaryWrapper>
        <Title>{title}</Title>
        <Description>{description}</Description>
        <ElapsedTime>{getElapsedTime(createdAt)}</ElapsedTime>
      </SummaryWrapper>
    </AlarmPreviewWrapper>
  );
};
```
<br><br>

### 💡 필요한 후속작업이 있어요.
- (없다면 이 문항을 지워주세요.)
<br><br>

### 💡 다음 자료를 참고하면 좋아요.
- (없다면 이 문항을 지워주세요.)
<br><br>

### ✅ 셀프 체크리스트

- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [ ] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [ ] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-05-14 15:27 UTC, abiriadev commented on src/Components/AlarmInBox/AlarmInbox.stories.ts
> +        title: '루도루도루도~~~',
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-14 15:35 UTC, abiriadev requested changes

2024-05-14 15:35 UTC, abiriadev commented on src/utils/date.ts
> +};
어려운 로직이셨을 텐데 정말 섬세하게 잘 구현하신 것 같습니다!

:clap::clap::clap::clap:

비슷한 기능이 `date-fns` 등 여러 라이브러리에도 존재하니 한번 살펴보시면 더 영감을 받으실 수도 있을 것 같아요!
https://date-fns.org/v3.6.0/docs/formatDistanceToNow

2024-05-14 15:35 UTC, abiriadev commented on src/Components/AlarmInBox/index.tsx
> +  border-bottom-right-radius: ${({ theme, isOpen }) => !isOpen && theme.borderRadius.small};
`isOpen`을 사용해 border를 아래쪽만 바꾸는 게 정말 섬세함이 느껴지네요 :+1:

2024-05-14 15:35 UTC, abiriadev commented on src/Components/AlarmInBox/index.tsx
> +    border-bottom-right-radius: ${({ theme }) => theme.borderRadius.small};
인박스 하단에 border를 주기 위해 정말 많은 고민을 하신 게 느껴집니다!

2024-05-14 15:36 UTC, abiriadev approved these changes

2024-05-16 00:15 UTC, SungHyun627 commented on src/utils/date.ts
> +};
참고하겠습니다!!

2024-05-16 00:16 UTC, SungHyun627 commented on src/Components/AlarmInBox/AlarmInbox.stories.ts
> +        title: '루도루도루도~~~',
ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-16 00:24 UTC, merged