토글스위치, 토글스위치 리스트 컴포넌트 구현 (WIP)
Ludo-SMP/ludo-frontend pull request #195
Opened 2024-05-14 10:58 UTC by hyosin-Jang

Closes #194 
</strong>

### 💡 다음 이슈를 해결했어요.
- 토글 스위치 컴포넌트를 추가했습니다.
- 토글 스위치 리스트 컴포넌트를 추가했습니다. 
<br><br>

https://github.com/Ludo-SMP/ludo-frontend/assets/71035113/9ea2835a-ffee-4c5a-8c03-442898e2e5f8

### 💡 이슈를 처리하면서 추가된 코드가 있어요.

### 💡 필요한 후속작업이 있어요.
- Accordion 컴포넌트에서 padding, typo를 제외하면 UI가 비슷해서 재사용할지 검토해보겠습니다!
- 스토리 파일 작업중입니다!

### 💡 다음 자료를 참고하면 좋아요.
- css `::before`, `::after`, `:checked`를 이용해서 좌우로 움직이는 원(thumb) 구현 
https://oizys.tistory.com/69
- 가상요소 선택자 순서 `::before:hover` (x) -> `:hover::before` (o)
https://stackoverflow.com/questions/5777210/how-can-i-write-a-hover-condition-for-abefore-and-aafter

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [x] 변경 후 코드는 기존의 테스트를 통과합니다.
- [x] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-05-19 08:44 UTC, SungHyun627 approved these changes
코드 자체에 섬세함을 느낄 수 있었던 것 같습니다. 덕분에 자주 사용하지 않았던 css 속성, 우선순위, 웹 접근성 등에 대해 학습할 수 있었습니다. 수고 많으셨습니다. 👍

2024-05-19 08:44 UTC, SungHyun627 commented on src/Components/ToggleSwitch/index.tsx
> +`;
체크되었을 때, hover되었을 때, 비활성화 되었을 때, 포커스 되었을 때 css를 정말 상세하게 잘 작성해주신 것 같아요 👍.

2024-05-19 08:44 UTC, SungHyun627 commented on src/Components/ToggleSwitch/index.tsx
> +    if (ref && typeof ref !== 'function') {
ref타입이 `MutableRefObject` 일때 clicked state를 바꿔주는 로직이군요 👍

2024-05-19 08:44 UTC, SungHyun627 commented on src/Components/ToggleSwitch/index.tsx
> +      <Switch type="checkbox" role="switch" $isChecked={clicked} onChange={handleChange} disabled={disabled} />
웹 접근성을 고려하여 `role` 속성 사용하신 부분 좋습니다👍

2024-05-19 08:44 UTC, SungHyun627 commented on src/Styles/globalStyles.ts
> +
checkbox 타입의 input의 appearance 속성을 global로 정의해 주셨네요 👍

2024-05-19 08:44 UTC, SungHyun627 commented on src/Components/ToggleSwitch/index.tsx
> +
가상 클래스(:), 가상 요소(::) 우선순위에 대해 다시 한번 찾아보게 되는 코드네요!!

2024-05-21 07:50 UTC, abiriadev requested changes
@hyosin-Jang `calc()`함수와 가상 선택자들을 정말 다양하게 활용하신 멋진 코드였습니다!

정말 보고 배울 점이 많은 코드였습니다!

2024-05-21 07:50 UTC, abiriadev commented on src/Components/ToggleSwitch/index.tsx
> +    transition: background-color: 0.3s linear;
@hyosin-Jang 

```suggestion
    transition: left 0.15s ease;
  }

  /** 체크된 상태 */
  &:checked {
    background-color: ${({ theme }) => theme.color.purple1};
    transition: background-color: 0.15s ease;
```

트랜지션에 0.3초를 설정하셨는데, 시간을 조금만 줄이면 조금 더 자연스러운 움직임이 나올 것 같습니다!

1. 너무 느린 트랜지션은 사용자가 랙인가? 하고 당황하게 만들 수 있음
2. 트랜지션이 느리면 빠른 취소(ToggleSwitch의 경우 껐다켰다 반복) 동작에서 트랜지션이 실행되던 도중 초기화되어 트랜지션이 끊겨 보일 수 있음
3. linear트랜지션은 움직임이 다소 부자연스럽게 보일 수 있음 (근거 없음)

### 사례 분석

- MUI/Material UI: (https://mui.com/material-ui/react-switch/)
  `150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms`
- Microsoft Fluent UI: (https://628d031b55e942004ac95df1-erpbszpmve.chromatic.com/?path=/story/components-switch--default)
  `0.2s cubic-bezier(0.33, 0, 0.67, 1)`
- Mantine: (https://mantine.dev/core/switch/)
  `0.15s ease`
- Ant Design: (https://ant.design/components/switch)
  `0.2s ease-in-out`

현재 `0.3`의 절반인 `0.15`, `linear`보단 더 자연스러운 `ease`를 적용해 보았습니다. (임시)

### `0.3 linear`

https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/4df3144d-bf86-4cb3-a883-cf2cf9625da2

### `0.15 ease`

https://github.com/Ludo-SMP/ludo-frontend/assets/72962900/7495545f-6cd1-4c87-afd4-fc70ab9ddecd

이러한 값은 임의로 정해진 것이며, 제안일 뿐이니 고려만 부탁드립니다!

2024-05-21 07:50 UTC, abiriadev commented on src/Components/ToggleSwitch/index.tsx
> +  }
JS의 조건문 등을 사용하지 않고 CSS에 내장된 선택자만을 사용하셔서 구현하시는 점이 멋집니다.

2024-05-21 07:50 UTC, abiriadev commented on src/Components/ToggleSwitch/index.tsx
> +        left: calc(100% - 24px - 6px);
위치를 수동으로 지정하지 않고 `calc()` 함수를 사용해서 상대적인 위치로 이동시키는 코드가 깔끔합니다!

2024-05-21 07:50 UTC, abiriadev commented on src/Components/ToggleSwitch/index.tsx
> +        height: 24px;
스위치가 토글될 때 Thumb의 크기까지 바꾸시는 사소한 디테일이 훌륭한 것 같습니다.

2024-05-21 07:50 UTC, abiriadev commented on src/Components/ToggleSwitchList/index.tsx
> +});
RHF과 연동하기 쉽도록 `forwardRef`를 적절히 사용해 주셔서 작업이 훨씬 간단해 질 것 같습니다! :+1:

2024-05-21 10:18 UTC, hyosin-Jang commented on src/Components/ToggleSwitch/index.tsx
> +    transition: background-color: 0.3s linear;
@abiriadev 
트랜지션 시간은 깊게 고민하지 못했는데, 올려주신 영상과 다른 라이브러리 사례를 참고하니
시간을 짧게 가져가는게 좀 더 자연스러워 보이네요!

timing-funciton도 스위치의 특성을 고려하면 ease가 더 자연스러운 것 같습니다.
덕분에 다른 라이브러리에서 스위치가 어떻게 구현됐는지 비교해볼 수 있어서 좋았습니다. 👍

꼼꼼하고 유익한 피드백 주셔서 감사드립니다! 🙏

2024-05-21 11:09 UTC, abiriadev approved these changes
정말 수고하셨습니다! :+1::+1:

2024-05-21 11:13 UTC, merged