SP-563 사용자 출석 체크 버튼
Ludo-SMP/ludo-frontend pull request #217
Opened 2024-05-28 11:32 UTC by abiriadev

- **feat: 마크업 전부 수정 - 사이드바 구현 (SP-578)**
- **refactor: 컴포넌트로 반복 제거 (SP-578)**
- **refactor: 스타일상 대체 가능한 <SideBarMenuInner /> 컴포넌트 제거 (SP-578)**
- **refactor: 스타일상 대체 가능한 `<StudyEditButton />` 컴포넌트 정의 제거 (SP-578)**
- **chore: ? (SP-578)**
- **refactor: 마크업을 컴포넌트로 분리 (SP-578)**
- **feat: prop 데이터 삽입 (SP-578)**
- **feat: RRD 링크 연결 (SP-578)**
- **feat: 본문 내용 마크업 구현: 출석, 멤버 목록 (SP-578)**
- **feat: 출석 상단바 마크업 구현 (SP-578)**
- **feat: 응용 버튼 컴포넌트 구현 (SP-578)**
- **docs: 응용 버튼 스토리 추가 (SP-578)**
- **chore: 설명 추가 (SP-578)**
- **feat: 스터디원 구성원 명수 컴포넌트 구현 (SP-578)**
- **refactor: 텍스트, 콜백 함수를 prop으로 분리 (SP-578)**
- **feat: 스터디원 모집 페이지 링크 버튼 추가 (SP-578)**
- **feat: 디자인 변경에 맞게 `black0` 으로 수정 (SP-578)**
- **feat: 컴포넌트 단순화 (SP-578)**
- **feat: 죽은 코드 제거 (SP-578)**
- **refactor: 새 컨벤션에 맞게 디렉토리 dedent (SP-578)**
- **feat: 진행 기간, D-day 표시 (SP-578)**
- **feat: 진행 플랫폼, 진행 방식 표시 (SP-578)**
- **chore: ts-pattern 추가 (SP-578)**
- **feat: 상단 내비게이션에 스터디 상태 표시 (SP-578)**
- **refactor: 사이드바를 별도 컴포넌트로 분리 (SP-578)**
- **refactor: 죽은 코드 제거 (SP-578)**
- **refactor: 팀장 권한에 따른 버튼 숨김 & 표시 (SP-578)**
- **chore: 지원자는 별도 페이지로 분리됨 (SP-578)**
- **feat: 사용자 출석 모달 표시 기능 구현 (SP-563)**

### 💡 다음 이슈를 해결했어요.
- (가능한 한 자세히 작성해 주시면 도움이 됩니다.)
<br><br>
### 💡 이슈를 처리하면서 추가된 코드가 있어요.
- (없다면 이 문항을 지워주세요.)
<br><br>

### 💡 필요한 후속작업이 있어요.
- (없다면 이 문항을 지워주세요.)
<br><br>

### 💡 다음 자료를 참고하면 좋아요.
- (없다면 이 문항을 지워주세요.)
<br><br>

### ✅ 셀프 체크리스트

- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [ ] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ ] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ ] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [ ] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2024-06-03 01:54 UTC, hyosin-Jang requested changes

2024-06-03 01:54 UTC, hyosin-Jang commented on src/Pages/StudyDetail/index.tsx
> +  const { mutate: attendStudyMutate, isSuccess: isAttendStudyMutationSuccess } = useAttendStudyMutation(studyId);
mutation으로 훅을 만들어서 깔끔하게 구현해주셨네요 🙂
api 요청에서 400 번대 응답이 내려오는 경우도 고려해서 에러 처리도 해주면 좋을 것 같습니다!

2024-06-03 02:02 UTC, abiriadev commented on src/Pages/StudyDetail/index.tsx
> +  const { mutate: attendStudyMutate, isSuccess: isAttendStudyMutationSuccess } = useAttendStudyMutation(studyId);
꼼꼼한 리뷰 감사합니다!

아직 작업이 끝나지 않아서 여러 문제가 있을 수 있습니다!

2024-06-03 02:03 UTC, abiriadev commented on src/Pages/StudyDetail/index.tsx
> +  const { mutate: attendStudyMutate, isSuccess: isAttendStudyMutationSuccess } = useAttendStudyMutation(studyId);
꼼꼼한 리뷰 감사합니다!

아직 작업이 끝나지 않아서 여러 문제가 있을 수 있습니다!

2024-06-05 14:50 UTC, SungHyun627 approved these changes
출석 체크 button, 출석 API 및 Custom Hook 구현하시느라 고생하셨습니다👍

2024-06-05 14:50 UTC, SungHyun627 commented on src/Hooks/study/useAttendStudyMutation.ts
> +export const useAttendStudyMutation = (studyId: number) =>
Custom Hook으로 분리하신 부분 좋습니다👍

2024-06-05 14:50 UTC, SungHyun627 commented on src/Pages/StudyDetail/MemberSection.tsx
> +  flex-wrap: wrap;
MemberSection 너비 이상의 content가 들어올 경우 wrap되도록 설정해주신 부분 좋네요👍

2024-06-05 18:27 UTC, SungHyun627 approved these changes
사용하지 않는 함수 및 라이브러리 제거한 부분 확인했습니다. 수고하셨습니다.👍

2024-06-05 18:33 UTC, hyosin-Jang approved these changes
석 API에서 오늘 날짜로 출석체크 확인하도록 구현하신 것, 출석체크 후 버튼 비활성화 로직, 
에러 모달 표시하신 것 확인했습니다.
늦은 시간까지 정말 고생많으셨습니다 !! 👍

2024-06-05 18:34 UTC, merged